### ISSUE TITLE
the graphql macro is being ignored

### ISSUE THREAD

**Issue by PumpedSardines** [graphql-rust/juniper#1140]
**Describe the bug**
the graphql macro is being ignored when used for parameters.

**To Reproduce**
Heres a snippet of my code. When entering the playground the parameter for user will be `userId` not `id`. 
```rs
use super::{resolvers, GraphQLContext};
use diesel::prelude::*;
use juniper::graphql_object;

pub struct Query;
#[graphql_object(context = GraphQLContext)]
impl Query {
    pub fn api_version() -> &'static str {
        "1.0"
    }

    pub fn user(
        context: &GraphQLContext,
        #[graphql(name = "id")] user_id: i32,
    ) -> Option<resolvers::user::User> {
        let pool = &context.pool;
        let conn = &mut pool.get().unwrap();

        use database::schema::users;

        let user = users::table
            .filter(users::id.eq(user_id))
            .first::<database::models::User>(conn)
            .optional()
            .expect("Error loading users");

        if user.is_none() {
            return None;
        }

        let user = user.unwrap();

        Some(resolvers::user::User {
            id: user_id,
            username: user.username,
        })
    }
}
```

**Expected behavior**
The parameter name should be `id` not `userId`

**Additional context**
When running the `juniper_actix` example this does not happen.

Here's my Config.toml:
```toml
[package]
name = "graphql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
database = { path = "../database" }
r2d2 = "0.8.9"
juniper = { version = "0.15.10", features = ["expose-test-schema"] }
diesel = { version = "2.0.0", features = ["postgres", "r2d2"] }
```
