### ISSUE TITLE
Switch to Azure Pipelines

### ISSUE THREAD

**Issue by LegNeato** [graphql-rust/juniper#259]
AppVeyor is super flaky.

It looks like https://azure.microsoft.com/en-us/services/devops/pipelines/ supports all platforms and would be really fast:

"Get cloud-hosted pipelines for Linux, macOS, and Windows with unlimited minutes and 10 free parallel jobs for open source"

We could switch to one CI instead of maintaining multiple.

**Comment by theduke** [comment]
Yeah that also is the intention behind https://github.com/graphql-rust/juniper/pull/213.
Caveat is that Cirrus does not support Rust on Windows easily so I gave up there.
If Azure works well I'm all for it.

**Comment by kaylangan** [comment]
I'm a Program Manager on Azure Pipelines. Let me know if you have any questions or suggestions. I'm happy to help!

**Comment by LegNeato** [comment]
@kaylangan great, thanks! Do you know of any Rust projects currently using Azure Pipelines we could take a look at?

**Comment by LegNeato** [comment]
@kaylangan I want to have am N*M matrix of jobs, similar to what we have in Travis now (rust version * platform). It doesn't appear we can do that easily?

When I do something like:

```yaml
strategy:
  matrix:
    stable:
      rustup_toolchain: stable
    beta:
      rustup_toolchain: beta
    nightly:
      rustup_install: nightly
    minimum_supported_version_plus_one:
      rustup_toolchain: 1.23.0
    minimum_supported_version:
      rustup_toolchain: 1.22.0

jobs:
- template: _build/job.yml 
  parameters:
    name: macOS
    pool:
      vmImage: 'macOS-10.13'

- template: _build/job.yml
  parameters:
    name: Linux
    pool:
      vmImage: 'Ubuntu-16.04'

- template: _build/job.yml
  parameters:
    name: Windows
    pool:
      vmImage: 'vs2017-win2016'
```

I get an error `azure-pipelines.yml (Line: 14, Col: 1): 'jobs' is not allowed. 'strategy' is already defined and is mutually exclusive.`
