### ISSUE TITLE
Rocket 0.4.0-rc.2 multiple packages link to native library

### ISSUE THREAD

**Issue by johansmitsnl** [graphql-rust/juniper#287]
When I add juniper to the Rocket project I get this error:

```toml
[package]
name = "backend"
version = "0.1.0"
publish = false

[dependencies]
rocket = "0.4.0-rc.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
# GraphQL
juniper = "0.10"
juniper_rocket = "0.1"

[dependencies.rocket_contrib]
version = "0.4.0-rc.2"
default-features = false
features = ["handlebars_templates", "serve"]
```

```
cargo run
error: multiple packages link to native library `ring-asm`, but a native library can be linked only once

package `ring v0.11.0`
    ... which is depended on by `cookie v0.9.2`
    ... which is depended on by `rocket v0.3.17`
    ... which is depended on by `rocket_codegen v0.3.17`
    ... which is depended on by `juniper_rocket v0.1.3`
    ... which is depended on by `backend v0.1.0 (backend)`
links to native library `ring-asm`

package `ring v0.13.5`
    ... which is depended on by `cookie v0.11.0`
    ... which is depended on by `rocket_http v0.4.0-rc.2`
    ... which is depended on by `rocket v0.4.0-rc.2`
    ... which is depended on by `rocket_contrib v0.4.0-rc.2`
    ... which is depended on by `backend v0.1.0 (backend)`
also links to native library `ring-asm`
```

Is this an issue on my side or
