### ISSUE TITLE
Publish juniper_rocket 0.4

### ISSUE THREAD

**Issue by Kilerd** [graphql-rust/juniper#292]
I notice that PR #277 updated rocket's version to 0.4.0, but not modified juniper_rocket's version.
so I can get the newest version of it in crates.io where juniper_rocket v0.1.3 still dependent on rocket ^0.3.9

so, please release a new fixed version.

**Comment by LegNeato** [comment]
Yeah, I haven't pushed updated crates yet. I plan to do it tonight or tomorrow.

**Comment by sssilver** [comment]
Blocked on this as well.

**Comment by theduke** [comment]
You can always just use a git dependency in the meantime.

```toml
[dependencies]
juniper_rocket = { git = "https://github.com/graphql-rust/juniper.git" }
```
